// Auto-generated by LibreLane
module top_soc(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input wb_clk_i,
  input wb_rst_i,
  input wbs_cyc_i,
  input wbs_stb_i,
  input wbs_we_i,
  input[3:0] wbs_sel_i,
  input[31:0] wbs_adr_i,
  input[31:0] wbs_dat_i,
  output wbs_ack_o,
  output[31:0] wbs_dat_o,
  input[11:0] adc_data_in,
  output[2:0] user_irq
);
endmodule
